# Generated by Django 5.2.5 on 2025-08-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro_conductores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("cantante", models.BooleanField(default=False)),
                ("instrumento", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ArtistaGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ingreso", models.DateField()),
                ("creacion_registro", models.DateField(auto_now_add=True)),
                ("agregado_por", models.CharField(max_length=50)),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="registro_conductores.artista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fecha_creacion", models.DateField()),
                (
                    "artistas",
                    models.ManyToManyField(
                        related_name="grupos",
                        through="registro_conductores.ArtistaGrupo",
                        to="registro_conductores.artista",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artistagrupo",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registro_conductores.grupo",
            ),
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albumes",
                        to="registro_conductores.grupo",
                    ),
                ),
            ],
        ),
    ]
